# Travis CI configuration file for WordPoints.

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - TRAVISCI_RUN=codesniff
    - TRAVISCI_RUN=phpunit WP_VERSION=nightly
    - TRAVISCI_RUN=phpunit WP_VERSION=latest
    - TRAVISCI_RUN=phpunit WP_VERSION=4.0
    - TRAVISCI_RUN=phpunit WP_VERSION=3.9
    - TRAVISCI_RUN=phpunit WP_VERSION=3.8

sudo: false

matrix:
  include:
    # Only run HHVM against the latest for now.
    - php: hhvm
      env: TRAVISCI_RUN=phpunit WP_VERSION=latest
  exclude:
    # The codesniff pass only needs to be run once.
    - php: 5.4
      env: TRAVISCI_RUN=codesniff
    - php: 5.5
      env: TRAVISCI_RUN=codesniff
    - php: 5.6
      env: TRAVISCI_RUN=codesniff
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
    - export WORDPOINTS_PROJECT_TYPE=wordpoints
    - export DEV_LIB_PATH=dev-lib-wordpoints
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - codesniff-php-syntax
    - codesniff-phpcs
    - codesniff-jshint
    - codesniff-l10n
    - codesniff-xmllint
    - phpunit-basic
    - phpunit-ms
    - phpunit-ms-network
    - phpunit-uninstall
    - phpunit-ms-uninstall
    - phpunit-ms-network-uninstall
    - phpunit-ajax
    - phpunit-ms-ajax
    - phpunit-ms-network-ajax

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
