# Travis CI configuration file for WordPoints.

language: php

php:
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4

env:
    - TRAVISCI_RUN=codesniff
    - TRAVISCI_RUN=phpunit WP_VERSION=develop
    - TRAVISCI_RUN=phpunit WP_VERSION=4.8
    - TRAVISCI_RUN=phpunit WP_VERSION=4.7

dist: trusty

sudo: false

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

matrix:
  include:
    # Use Ubuntu Precise because Trusty doesn't support PHP 5.2 or 5.3.
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=develop
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.8
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.7
    - php: 5.2
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=develop
    - php: 5.2
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.8
    - php: 5.2
      dist: precise
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.7
    # Only run nightly against trunk.
    - php: nightly
      env: TRAVISCI_RUN=phpunit WP_VERSION=develop
  exclude:
    # The codesniff pass only needs to be run once.
    - php: 7.2
      env: TRAVISCI_RUN=codesniff
    - php: 7.0
      env: TRAVISCI_RUN=codesniff
    - php: 5.6
      env: TRAVISCI_RUN=codesniff
    - php: 5.5
      env: TRAVISCI_RUN=codesniff
    - php: 5.4
      env: TRAVISCI_RUN=codesniff
  allow_failures:
    - php: nightly
    - php: 7.2
  fast_finish: true

before_script:
    - export WORDPOINTS_PROJECT_TYPE=wordpoints
    - export DEV_LIB_PATH=dev-lib
    - if [ -e .wordpoints-dev-lib-config.sh ]; then source .wordpoints-dev-lib-config.sh; fi
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - codesniff-php-syntax
    - codesniff-php-autoloaders
    - codesniff-phpcs
    - codesniff-strings
    - codesniff-dittography
    - codesniff-jshint
    - codesniff-l10n
    - codesniff-xmllint
    - codesniff-bash
    - codesniff-symlinks
    - phpunit-basic
    - phpunit-ms
    - phpunit-ms-network
    - phpunit-uninstall
    - phpunit-ms-uninstall
    - phpunit-ms-network-uninstall
    - phpunit-ajax
    - phpunit-ms-ajax
    - phpunit-ms-network-ajax
    - wpcept-run
    - WORDPOINTS_NETWORK_ACTIVE=1 WP_MULTISITE=1 wpcept-basic acceptance network

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
