# Travis CI configuration file for WordPoints.

language: php

# 5.3 runs first so that we can fail fast on the codesniff pass (see below).
php:
    - 5.3
    - 5.2
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - TRAVISCI_RUN=codesniff
    - TRAVISCI_RUN=phpunit WP_VERSION=master
    - TRAVISCI_RUN=phpunit WP_VERSION=4.6

sudo: false

matrix:
  include:
    # Only run HHVM against trunk for now.
    - php: hhvm
      env: TRAVISCI_RUN=phpunit WP_VERSION=master
    # Only run nightly against trunk.
    - php: nightly
      env: TRAVISCI_RUN=phpunit WP_VERSION=master
  exclude:
    # The codesniff pass only needs to be run once, I chose PHP 5.3, since WPCS requires it.
    - php: 5.2
      env: TRAVISCI_RUN=codesniff
    - php: 5.4
      env: TRAVISCI_RUN=codesniff
    - php: 5.5
      env: TRAVISCI_RUN=codesniff
    - php: 5.6
      env: TRAVISCI_RUN=codesniff
    - php: 7.0
      env: TRAVISCI_RUN=codesniff
    - php: 7.1
      env: TRAVISCI_RUN=codesniff
    - php: 7.1
      env: TRAVISCI_RUN=phpunit WP_VERSION=4.6
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
    - export WORDPOINTS_PROJECT_TYPE=wordpoints
    - export DEV_LIB_PATH=dev-lib
    - if [ -e .wordpoints-dev-lib-config.sh ]; then source .wordpoints-dev-lib-config.sh; fi
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - codesniff-php-syntax
    - codesniff-php-autoloaders
    - codesniff-phpcs
    - codesniff-strings
    - codesniff-jshint
    - codesniff-l10n
    - codesniff-xmllint
    - codesniff-bash
    - codesniff-symlinks
    - phpunit-basic
    - phpunit-ms
    - phpunit-ms-network
    - phpunit-uninstall
    - phpunit-ms-uninstall
    - phpunit-ms-network-uninstall
    - phpunit-ajax
    - phpunit-ms-ajax
    - phpunit-ms-network-ajax
    - wpcept-run
    - WORDPOINTS_NETWORK_ACTIVE=1 WP_MULTISITE=1 wpcept-basic acceptance network

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
